"""
模型默认数据
参考来源：https://api.heabl.top/api/pricing
"""
DEFAULT_MODELS = [
    {
        "model_id": "gpt-5",
        "display_name": "GPT-5",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.625,
        "output_price": 5.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "gpt-5.1",
        "display_name": "GPT-5.1",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.625,
        "output_price": 5.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "gpt-5.4",
        "display_name": "GPT-5.4",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 1.25,
        "output_price": 7.5,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "gpt-5.4-mini",
        "display_name": "GPT-5.4 Mini",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.375,
        "output_price": 2.25,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "gpt-5-codex",
        "display_name": "GPT-5 Codex",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.625,
        "output_price": 5.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": ["gpt-5.1-codex", "gpt-5.2-codex", "gpt-5.3-codex"],
        "remark": "Codex 常用模型，价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "gpt-5-codex-mini",
        "display_name": "GPT-5 Codex Mini",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.125,
        "output_price": 1.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": ["gpt-5.1-codex-mini"],
        "remark": "Codex 低成本模型，价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "deepseek-chat",
        "display_name": "DeepSeek Chat",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.125,
        "output_price": 0.35,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "deepseek-reasoner",
        "display_name": "DeepSeek Reasoner",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.2,
        "output_price": 0.85,
        "is_active": True,
        "is_recommended": False,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "grok-4.5",
        "display_name": "Grok 4.5",
        "provider": "grok",
        "protocol": "openai_responses",
        "input_price": 0.0,
        "output_price": 0.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": True,
        "supports_gemini": False,
        "aliases": [],
        "remark": "Grok CLI / Claude Code 中转常用模型，价格按上游为准",
    },
    {
        "model_id": "grok-4",
        "display_name": "Grok 4",
        "provider": "grok",
        "protocol": "openai_responses",
        "input_price": 1.5,
        "output_price": 7.5,
        "is_active": True,
        "is_recommended": False,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "支持 responses，价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "grok-3-mini",
        "display_name": "Grok 3 Mini",
        "provider": "openai",
        "protocol": "openai_responses",
        "input_price": 0.15,
        "output_price": 0.25,
        "is_active": True,
        "is_recommended": False,
        "supports_codex": True,
        "supports_claudecode": False,
        "supports_gemini": True,
        "aliases": [],
        "remark": "支持 responses，价格参考 api.heabl.top/api/pricing",
    },
    {
        "model_id": "claude-3-7-sonnet-20250219",
        "display_name": "Claude 3.7 Sonnet",
        "provider": "claude",
        "protocol": "anthropic_messages",
        "input_price": 3.0,
        "output_price": 15.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": False,
        "supports_claudecode": True,
        "supports_gemini": False,
        "aliases": ["claude-3-7-sonnet"],
        "remark": "ClaudeCode 推荐模型",
    },
    {
        "model_id": "claude-3-5-sonnet-20241022",
        "display_name": "Claude 3.5 Sonnet",
        "provider": "claude",
        "protocol": "anthropic_messages",
        "input_price": 3.0,
        "output_price": 15.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": False,
        "supports_claudecode": True,
        "supports_gemini": False,
        "aliases": ["claude-3-5-sonnet"],
        "remark": "ClaudeCode 常用模型",
    },
    {
        "model_id": "qwen3.6-plus",
        "display_name": "Qwen 3.6 Plus",
        "provider": "openai",
        "protocol": "openai_chat",
        "input_price": 0.8,
        "output_price": 2.0,
        "is_active": True,
        "is_recommended": True,
        "supports_codex": True,
        "supports_claudecode": True,
        "supports_gemini": True,
        "aliases": ["qwen3.6-plus-latest"],
        "remark": "兼容 OpenAI/Claude 代理场景",
    },
]
